services:
  redis:
    image: redis:alpine
    ports:
      - "6380:6379"

  web:
    build: .
    # Add 'sh -c' to ensure the command runs in a shell environment
    command: sh -c "python manage.py customcreatesuperuser"  "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    # Set the working directory so it knows where manage.py is
    working_dir: /app
    ports:
      - "9292:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
    restart: always

  celery_worker:
    build: .
    command: celery -A santosh worker -l info
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
    restart: always

  celery_beat:
    build: .
    command: celery -A santosh beat -l info
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
    restart: always



  